# Generated by Django 6.0.6 on 2026-06-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('merchant', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('Santander', 'Santander'), ('MB WAY', 'MB WAY')], max_length=20)),
            ],
        ),
    ]
