# Generated by Django 6.0.6 on 2026-06-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='raw_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
